[package]
name = "expectest"
version = "0.3.1"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

description = "Crate provides matchers and matcher functions for unit testing."
repository = "https://github.com/zummenix/expectest"
readme = "./README.md"
keywords = ["unit", "test", "matcher", "expect"]

license = "MIT"

[dependencies]
num = { version = "0.1.28", default-features = false }

