[package]
name = "expectest"
version = "0.2.0"
authors = ["Aleksey Kuznetsov <zummenix@gmail.com>"]

description = "Crate provides matchers and matcher functions for unit testing. (WIP)"
repository = "https://github.com/zummenix/expectest"
readme = "./README.md"
keywords = ["unit", "test", "matcher", "expect"]

license = "MIT"

[dependencies]
num = "0.1.*"
